# Generated by Django 4.1.6 on 2023-03-20 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patients",
            fields=[
                ("fname", models.CharField(max_length=50)),
                ("lname", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("address", models.TextField()),
                ("email", models.EmailField(max_length=30)),
                ("phone", models.CharField(max_length=30)),
            ],
        ),
    ]
