# Generated by Django 4.1.6 on 2023-03-07 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="patient", name="date_of_birth",),
    ]
