# Generated by Django 4.1.7 on 2023-04-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_patient_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="age",
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                default="Unknown",
                max_length=1,
            ),
        ),
    ]
