# Generated by Django 4.1.7 on 2023-04-05 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_patient_age_patient_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="Insurance_plans",
            fields=[
                ("pl_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("desc", models.TextField()),
                (
                    "i_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.insuranceprovider",
                    ),
                ),
            ],
        ),
    ]
