# Generated by Django 4.1.7 on 2023-04-05 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_availability"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient_History",
            fields=[
                ("r_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("description", models.TextField()),
                (
                    "p_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.patient"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Patient History",
            },
        ),
    ]
