# Generated by Django 4.1.7 on 2023-04-05 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_schedule_app"),
    ]

    operations = [
        migrations.RenameField(
            model_name="availability",
            old_name="d_id",
            new_name="doctor_id",
        ),
        migrations.RenameField(
            model_name="doctor_rating",
            old_name="d_id",
            new_name="doctor_id",
        ),
        migrations.RenameField(
            model_name="insurance_plans",
            old_name="desc",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="insurance_plans",
            old_name="i_id",
            new_name="insurance_id",
        ),
        migrations.RenameField(
            model_name="insurance_plans",
            old_name="pl_id",
            new_name="plan_id",
        ),
        migrations.RenameField(
            model_name="patient_history",
            old_name="p_id",
            new_name="patient_id",
        ),
        migrations.RenameField(
            model_name="patient_history",
            old_name="r_id",
            new_name="report_id",
        ),
        migrations.RenameField(
            model_name="schedule_app",
            old_name="d_id",
            new_name="doctor_id",
        ),
        migrations.RenameField(
            model_name="schedule_app",
            old_name="p_id",
            new_name="patient_id",
        ),
    ]
